### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by andreahm99** [ULL-ESIT-INF-DSI-2122/ull-esit-inf-dsi-21-22-prct11-async-sockets-alu0101119137#1]
@esegredo 
Buenas profe, tengo más o menos el código del ejercicio y ya algunos métodos me funcionan, pero estoy probando a hacer las pruebas y no me salen. Creo para las pruebas una instancia de mi clase Cliente, pero claro como hago para que se le pase un socket y se le pueda comprobar los datos que se le envían son correctos?

**Comment by esegredo** [comment]
Hola Andrea, buenas tardes.

La verdad es que es difícil darte una respuesta por aquí. Lo ideal hubiera sido una tutoría para que me explicaras un poco como quieres hacer.

Intenta que los métodos que ejecutan código asíncrono, por ejemplo, el del cliente que lleva a cabo una petición y espera por una respuesta del servidor, siga el patrón *callback* o utilice promesas. En ese caso, podrás probar muy fácilmente los métodos siguiendo lo que explico en los apuntes, al final de la sección del patrón *callback* y al final de la sección de promesas.

Saludos.
